// Generated by scripts/vynx_brand.py. No credentials or API configuration.
abstract final class VynxBrand {
  static const name = 'VynxDesk';
  static const website = "https://vynx.com.tr/";
  static const product = "https://vynx.com.tr/vynxdesk/";
  static const downloads = "https://vynx.com.tr/vynxdesk/#downloads";
  static const privacy = "https://vynx.com.tr/vynxdesk/privacy.html";
  static const pricing = "https://vynx.com.tr/vynxdesk/#service";
  static const changelog = "https://vynx.com.tr/vynxdesk/#changes";
  static const source = "https://vynx.com.tr/vynxdesk/#source";
  static const support = "https://vynx.com.tr/";
}
