#!/usr/bin/env python3
"""Generate and check VYNX product links; this never provisions endpoints."""
import argparse
import json
from pathlib import Path
from urllib.parse import urlsplit

ROOT = Path(__file__).resolve().parents[1]
LINKS = ('website', 'product', 'downloads', 'privacy', 'pricing', 'changelog', 'source', 'support')


def render(profile: dict) -> str:
    if set(profile) != {'name', 'managed_api', 'relay_host', *LINKS} or profile['name'] != 'VynxDesk':
        raise ValueError('Invalid VYNX brand profile')
    for name in LINKS:
        value = profile[name]
        if not isinstance(value, str): raise ValueError('Invalid VYNX product URL')
        url = urlsplit(value)
        if (url.scheme != 'https' or url.netloc != 'vynx.com.tr' or url.query or
                not url.path.startswith('/') or '\\' in value or '%' in value or '$' in value or
                any(ord(c) < 33 or ord(c) > 126 for c in value)):
            raise ValueError('Invalid VYNX product URL')
    if profile['managed_api'] != 'https://desk-api.vynx.com.tr' or profile['relay_host'] != 'desk-relay.vynx.com.tr':
        raise ValueError('Invalid VYNX deployment identity')
    lines = ['// Generated by scripts/vynx_brand.py. No credentials or API configuration.',
             'abstract final class VynxBrand {', "  static const name = 'VynxDesk';"]
    for name in LINKS:
        # JSON escaping produces a valid Dart string for validated ASCII URLs.
        lines.append(f'  static const {name} = {json.dumps(profile[name])};')
    return '\n'.join([*lines, '}', ''])


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--profile', type=Path, default=ROOT / 'ops/vynx/brand.json')
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument('--check', action='store_true')
    mode.add_argument('--write', action='store_true')
    args = parser.parse_args()
    try:
        content = render(json.loads(args.profile.read_text(encoding='utf-8')))
        output = ROOT / 'flutter/lib/common/brand_links.dart'
        if args.write: output.write_text(content, encoding='utf-8')
        elif not output.is_file() or output.read_text(encoding='utf-8') != content:
            raise ValueError('Generated VYNX links differ from the profile')
    except (OSError, ValueError, KeyError, TypeError):
        parser.exit(1, 'VYNX profile validation failed; check canonical URLs and generated links.\n')
    print('VYNX product link contract passed; deployment is not verified.')


if __name__ == '__main__':
    main()
